//importe Google Fonts
import { Inter } from 'next/font/google' 
//importe css
import './globals.css'

//instância da font inter
const inter = Inter({ subsets: ['latin'] })
//definir metadata
export const metadata = {
  title: 'Jogos Vorazes',
  description: 'Generated by create next app',
}
//definir componente RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
